#
# Build stage
#
FROM maven:3.8.2-jdk-11 AS build
COPY . .
RUN mvn clean package -DskipTests

#
# Package stage
#
FROM openjdk:11-jdk-slim
COPY --from=build /target/basic-spring-boot-render-1.0.0-SNAPSHOT.jar basic.jar
# ENV PORT=8080
EXPOSE 80
ENTRYPOINT ["java","-jar","basic.jar"]
